[settings]
experimental = true

[settings.npm]
package_manager = "bun"

[tools]
# Language runtimes
node = "22.22.1"
python = "3.14.6"
ruby = "3.3"
lua = "5.1"
zig = "latest"
elixir = "latest"
erlang = "latest"
go = "latest"
clojure = "1.12.5.1638"
java = "26.0.1"
rust = "latest"

# Language tooling
"pipx:ptpython" = "latest"
bun = "1.3.11"
uv = "0.10.11"
pipx = "latest"
cargo-binstall = "1.17.7"
"npm:typescript" = "5.1.3"
"pipx:ansible-lint" = "latest"
elixir-ls = "latest"

# Language servers
lua-language-server = "3.17.1"
"npm:typescript-language-server" = "5.1.3"
"npm:yaml-language-server" = "1.21.0"
"pipx:python-lsp-server" = "1.14.0"
"cargo:tree-sitter-cli" = "latest"

# NPM utilities
"npm:degit" = "latest"
"npm:rimraf" = "6.1.3"
"npm:@earendil-works/pi-coding-agent" = "latest"
"npm:@earendil-works/gondolin" = "latest"
# "npm:@oh-my-pi/pi-coding-agent" = "latest"
"npm:@electron/asar" = "latest"
"npm:js-beautify" = "latest"
"npm:wrangler" = "latest"

# Python utilities
"pipx:ufbt" = "latest"

# Rust utilities
"cargo:wasm-pack" = "latest"
"aqua:zola" = "latest"
"aqua:watchexec/cargo-watch" = "latest"

# Infra Tooling
"aqua:cilium/hubble" = "1.17.3"
cilium-cli = "0.19.4"

# Data tooling
"cargo:pqrs" = "latest"

# TUIs
"aqua:erikjuhani/basalt" = "latest"
"github:can1357/oh-my-pi" = "latest"
